apiVersion: v2 # Helm chart schema version
name: cartservice # Chart name shown in Helm list
description: A Helm chart for Cart Service # Brief purpose of the chart
type: application # Deployable workload
version: 0.1.0 # Chart release version
appVersion: "1.16.0" # Application/container version for display
