apiVersion: v2 # Helm chart schema version
name: emailservice # Chart name
description: A Helm chart for Email Service # Chart purpose
type: application # Deployable application chart
version: 0.1.0 # Chart release version
appVersion: "1.16.0" # Application version metadata
